#postgreSQL configuration
spring.datasource.url=jdbc:postgresql://dpg-d6kn9d1aae7s73ahe4eg-a.singapore-postgres.render.com/moneymanager_kan1
spring.datasource.username=moneymanager_kan1_user
spring.datasource.password=5zFxAemeyKbzPghqb3vYVL8qoFgE6LRy